import:
- ./build/taskctl/contexts.yaml
- ./build/taskctl/tasks.yaml

pipelines:
  build:
    - task: clean
    - task: buildnumber
    - task: _compile
      depends_on:
      - clean
      - buildnumber

  release:
  - task: buildnumber
  - task: _release
    depends_on:
      - buildnumber
    env:
      VERSION_NUMBER: $BUILDNUMBER
      API_KEY: $API_KEY
      NOTES:
      COMMIT_ID: $COMMIT_ID
      ARTIFACTS_DIR: $ARTIFACTS_DIR  
      REPONAME: $REPONAME